# Generated by Django 4.0.5 on 2022-06-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotsprings',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
