# Generated by Django 4.0.5 on 2022-06-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_app', '0003_hotsprings_geoposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotsprings',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
