# Generated by Django 4.0.5 on 2022-06-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotWater_app', '0002_alter_hotsprings_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotsprings',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='HotWater_app/media/photos'),
        ),
    ]
