# Generated by Django 4.0.5 on 2022-07-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotWater_app', '0003_alter_hotsprings_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotsprings',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
