# Generated by Django 4.0.5 on 2022-07-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotWater_app', '0004_alter_hotsprings_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotsprings',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
