# Generated by Django 4.0.5 on 2022-07-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotWater_app', '0007_hotsprings_telegram_id_hotsprings_whats_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotsprings',
            old_name='Telegram_ID',
            new_name='Telegram',
        ),
        migrations.RenameField(
            model_name='hotsprings',
            old_name='Whats_Up',
            new_name='WhatsApp',
        ),
    ]
